// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lylsxoupakajkuisjdfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bHN4b3VwYWthamt1aXNqZGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mzg3MjQsImV4cCI6MjA2MDMxNDcyNH0.xEf0CKMn3b3Oq2GHJjz0F2BoohdL6u9zf0TLB_Mt3eY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);